name: dotenv_plus
description: A powerful and flexible .env file parser for Dart, supporting nested keys, type conversion, and variable interpolation.
version: 1.0.0
repository: https://github.com/avesbox/dotenv_plus
homepage: https://github.com/avesbox/dotenv_plus
documentation: https://github.com/avesbox/dotenv_plus
topics:
  - configuration
  - dotenv

environment:
  sdk: '>=3.10.0 <4.0.0'

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
